// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuMkUyizFtg5UikF7HFwjxWt49VvAj62A',
    appId: '1:619321465387:web:9d6a4c75d4b497fe6ea86e',
    messagingSenderId: '619321465387',
    projectId: 'blog-93349',
    authDomain: 'blog-93349.firebaseapp.com',
    storageBucket: 'blog-93349.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbYTp5RIDDOXTtIgWcwmM2MbbOSuTXbo4',
    appId: '1:619321465387:android:93866a681c232b336ea86e',
    messagingSenderId: '619321465387',
    projectId: 'blog-93349',
    storageBucket: 'blog-93349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHXrayAXCNBJRIzBYSstvjeGBnIIB19-s',
    appId: '1:619321465387:ios:a0badda1c15e2edb6ea86e',
    messagingSenderId: '619321465387',
    projectId: 'blog-93349',
    storageBucket: 'blog-93349.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHXrayAXCNBJRIzBYSstvjeGBnIIB19-s',
    appId: '1:619321465387:ios:b049e537475c98b46ea86e',
    messagingSenderId: '619321465387',
    projectId: 'blog-93349',
    storageBucket: 'blog-93349.appspot.com',
    iosBundleId: 'com.example.product.RunnerTests',
  );
}
